version: '3.8'

services:
  24rp14703-php-4:
    image: php:8.2.12-apache
    container_name: 24rp14703-php-4
    volumes:
      - "C:/xampp/htdocs/test_git_docker:/var/www/html"
    ports:
    - "8090:80"